# Generated by Django 5.1.3 on 2024-12-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('product_name', models.TextField()),
                ('category', models.TextField()),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.CharField(max_length=10)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rating_count', models.IntegerField()),
            ],
        ),
    ]
