# Generated by Django 5.1.3 on 2024-12-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('name_tokens', models.TextField()),
                ('categories', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.CharField(max_length=10)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rating_count', models.IntegerField()),
            ],
        ),
    ]
